---
title: "CTT dan IRT DICHOTOMOUS"
author: "Heru Wiryanto"
date: "August 4, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##CTT punya Analisa
Ini hasil analisa data ujian matematika (benar/salah) yang diikuti 7130 orang dan 10 soal
```{r, echo=FALSE}
library(psychometric)
library(foreign)
dataset <- read.spss("mathg6.sav", to.data.frame=TRUE)
item.exam(dataset, discrim=TRUE)
alpha(dataset)
alpha.CI(0.7245, 10, 7130, level=0.95, onesided=FALSE)#alpha.CI(alpha, k, N, level = 0.90, onesided = FALSE)
mathg6<-dataset
```

## Analisa Rasch Model

```{r , echo=FALSE}
library(ltm)
mathg6.rasch<-rasch(mathg6, constraint=cbind(ncol(mathg6)+1, 1))
summary(mathg6.rasch)
plot(mathg6.rasch,type=c("ICC"))
plot(mathg6.rasch,type=c("IIC"), items=c(7))
plot(mathg6.rasch,type=c("IIC"), items=c(8))
plot(mathg6.rasch,type=c("IIC"), items=c(9))
plot(mathg6.rasch,type=c("IIC"))
plot(mathg6.rasch,type=c("IIC"), items=c(0))
information(mathg6.rasch, c(-10,10))  
vals <- plot(mathg6.rasch, type = "IIC", items = 0, plot = FALSE)
plot(vals[, "z"], 1 / sqrt(vals[, "info"]), type = "l", lwd = 2,xlab = "Ability", ylab = "Standard Error",main = "Standard Error of Measurement")
theta.rasch<-factor.scores(mathg6.rasch)
pp<-item.fit(mathg6.rasch)
pp
summary(theta.rasch$score.dat$z1)
sqrt(var(theta.rasch$score.dat$z1))
plot(theta.rasch)
```

#1PL Analisa
```{r, echo=FALSE}
mathg6.1pl<-rasch(mathg6)
summary(mathg6.1pl)
plot(mathg6.1pl,type=c("ICC"), items=c(7))
plot(mathg6.1pl,type=c("ICC"), items=c(8))
plot(mathg6.1pl,type=c("ICC"), items=c(9))
plot(mathg6.1pl,type=c("IIC"), items=c(7))
plot(mathg6.1pl,type=c("IIC"), items=c(8))
plot(mathg6.1pl,type=c("IIC"), items=c(9))
information(mathg6.1pl, c(-10,10)) 
information(mathg6.1pl, c(0,10)) 
plot(mathg6.1pl,type=c("IIC"), items=c(0))
vals <- plot(mathg6.1pl, type = "IIC", items = 0, plot = FALSE)
plot(vals[, "z"], 1 / sqrt(vals[, "info"]), type = "l", lwd = 2,xlab = "Ability", ylab = "Standard Error",main = "Standard Error of Measurement")
theta.1pl<-factor.scores(mathg6.1pl)
plot(theta.1pl) 
pp1<-item.fit(mathg6.1pl)
pp
summary(theta.1pl$score.dat$z1)
```

#2PL
```{r, echo=FALSE}
mathg6.2pl<-ltm(mathg6~z1)
mathg6.2pl
plot(mathg6.2pl,type=c("ICC"), items=c(1))
plot(mathg6.2pl,type=c("ICC"), items=c(2))
plot(mathg6.2pl,type=c("ICC"), items=c(3))
plot(mathg6.2pl,type=c("IIC"), items=c(1))
plot(mathg6.2pl,type=c("IIC"), items=c(2))
plot(mathg6.2pl,type=c("IIC"), items=c(3))
information(mathg6.2pl, c(-10,10))
plot(mathg6.2pl,type=c("IIC"), items=c(0))
plot(mathg6.2pl,type=c("IIC"))
vals <- plot(mathg6.2pl, type = "IIC", items = 0, plot = FALSE)
plot(vals[, "z"], 1 / sqrt(vals[, "info"]), type = "l", lwd = 2,xlab = "Ability", ylab = "Standard Error",main = "Standard Error of Measurement")
item.fit(mathg6.2pl)
theta.2pl<-factor.scores(mathg6.2pl)
plot(theta.2pl)
summary(theta.2pl$score.dat$z1) 
```

#3PL Analisa
```{r, echo=FALSE}
mathg6.3pl<-tpm(mathg6)
summary(mathg6.3pl)
plot(mathg6.3pl,type=c("ICC"), items=c(7,9))
plot(mathg6.3pl,type=c("IIC"), items=c(7,9))
information(mathg6.3pl, c(-10,10))
information(mathg6.3pl, c(0,10))
plot(mathg6.2pl,type=c("IIC"), items=c(0))
plot(mathg6.2pl,type=c("IIC"))
vals <- plot(mathg6.3pl, type = "IIC", items = 0, plot = FALSE)
plot(vals[, "z"], 1 / sqrt(vals[, "info"]), type = "l", lwd = 2,xlab = "Ability", ylab = "Standard Error",main = "Standard Error of Measurement")
item.fit(mathg6.3pl)
theta.3pl<-factor.scores(mathg6.3pl)
plot(theta.3pl)
summary(theta.3pl$score.dat$z1)
```
#Perbandingan 3 Model
```{r, echo=FALSE}
information(mathg6.1pl, c(-10,10))	
information(mathg6.2pl, c(-10,10)) 
information(mathg6.3pl, c(-10,10)) 
```

#Anova 3 Model
```{r, echo=FALSE}
anova(mathg6.1pl, mathg6.2pl)
anova(mathg6.2pl, mathg6.3pl)
```
