---
title: "Analisa Faktor BFI"
author: "Heru Wiryanto"
date: "August 8, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## PERSIAPAN DATA BFI
```{r echo=FALSE}
library(psych)
data(bfi)
attach(bfi)
head(bfi)

data <- na.omit(bfi)
summary(data)
```

## UJI BARTLET DAN KMO
```{r, echo=FALSE}
df<-data.frame(data)
str(df)

kmo <- function(x)
{
  x <- subset(x, complete.cases(x))
  r <- cor(x)    
  r2 <- r^2      
  i <- solve(r)  
  d <- diag(i)   
  p2 <- (-i/sqrt(outer(d, d)))^2 
  diag(r2) <- diag(p2) <- 0      
  KMO <- sum(r2)/(sum(r2)+sum(p2))
  MSA <- colSums(r2)/(colSums(r2)+colSums(p2))
  return(list(KMO=KMO, MSA=MSA))
}

uji_bart <- function(x)
{
  method <- "Bartlett's test of sphericity"
  data.name <- deparse(substitute(x))
  x <- subset(x, complete.cases(x))
  n <- nrow(x)
  p <- ncol(x)
  chisq <- (1-n+(2*p+5)/6)*log(det(cor(x)))
  df <- p*(p-1)/2
  p.value <- pchisq(chisq, df, lower.tail=FALSE)
  names(chisq) <- "Khi-squared"
  names(df) <- "df"
  return(structure(list(statistic=chisq, parameter=df, p.value=p.value,
                        method=method, data.name=data.name), class="htest"))
}

# MATRIX KORELASI
cor(df[1:25])
#HASIL UJI BARTLEET
uji_bart(df[1:25])
# HASIL UJI KMO
kmo(df[1:25])
```

```{r, echo=FALSE}
library(psych)
pcadata.r <- principal(df[1:25],nfactor=5,rotate="varimax",scores=T)
pcadata.r

plot(pcadata.r$values, type="b",ylab="Nilai Eigenvalues",xlab="Komponen yang terbentuk", lab=c(5,5,5))
```

#ANALISA Kluster 
```{r, echo=FALSE}
ic <- iclust(df[1:25])
summary(ic)
```

#HASIL HASIL ANALISA
```{r, echo=FALSE}
fa.lookup(pcadata.r,b5ind.dictionary[2])
fa.lookup(pcadata.r,b5ind.dictionary[2])
```


